### ISSUE TITLE
Requesting upgrade `prettytable-rs` to 0.10.0

### ISSUE THREAD

**Issue by chong1144** [barter-rs/barter-rs#15]
## Background
Unsoundness is found using the nightly toolchain with `prettytable-rs` version 0.8.0. Details are found in [issue](https://github.com/phsym/prettytable-rs/issues/145)

## Request
Could you please upgrade `prettytable-rs` to 0.10.0 which uses safe rust to convert `Table` to `TableSlice`.

## Contribution
I would love to contribute, but I failed to find the branch where `0.8.6` locates.

**Comment by chong1144** [comment]
@carpetmaker @just-a-stream looking forward to your reply. :)

**Comment by just-a-stream** [comment]
Hello @chong1144, thanks for raising this to my attention :)
- Barter-rs 0.8.7 now exists on this repositories master & develop branch. 
- In 0.8.7 we have upgraded prettytable-rs to 0.10.0 :)

**Comment by chong1144** [comment]
Thanks!!! Appreciate your kindness!
