### ISSUE TITLE
Project activity and Discord link

### ISSUE THREAD

**Issue by Ampsicora** [barter-rs/barter-rs#26]
I'm very interested in using barter for my project and I'm wondering if there are funds and solid plans / roadmap to maintain and further develop this library in the long term.

I also wanted to point out that the discord link in the "Getting Help" section is invalid

**Comment by brandonfrulla** [comment]
Here's an invite to the [Discord](https://discord.gg/JXmgrezK)! The community has recently forked the repo and we're planning on establishing a clear roadmap soon! Perfect time to get involved

**Comment by carpetmaker** [comment]
> I'm very interested in using barter for my project and I'm wondering if there are funds and solid plans / roadmap to maintain and further develop this library in the long term.
\
I also wanted to point out that the discord link in the "Getting Help" section is invalid

It seems that the author @just-a-stream has been unreachable for some time now. Although I've also been inactive for a while, as one of the original maintainers and contributors with full access to all the project repos, I'm now looking to take the lead on the project again.

> Here's an invite to the [Discord](https://discord.gg/JXmgrezK)! The community has recently forked the repo and we're planning on establishing a clear roadmap soon! Perfect time to get involved

As @brandonfrulla suggested, you are warmly invited to join our [Discord](https://discord.gg/wE7RqhnQMV). However, contrary to his advice, I recommend that you concentrate your contribution efforts on this repo. I truly believe that fragmenting our still-relatively-small community further is unnecessary. Everyone can now contribute here again and also request to join the Barter GitHub organization.

**Comment by just-a-stream** [comment]
I'm back baby!

**Comment by just-a-stream** [comment]
I'll be adding new features & engaging with those who want to contribute in the coming weeks. Feel free to drop me a line on the discord if you want to chat. Closing this :)
