### ISSUE TITLE
Make barter-rs use a monorepo instead of multiple repositories

### ISSUE THREAD

**Issue by liamwh** [barter-rs/barter-rs#33]
Using a monorepo will make maintenance and CI/CD easier.

Tokio can be used as a good example of how this is best done in Rust: https://github.com/tokio-rs/tokio

**Comment by just-a-stream** [comment]
Hey @liamwh, I started the process [here](https://github.com/barter-rs/barter-rs/pull/new/refactor/monorepo_workspace_barter_ecosystem), but i'm not entirely sure what changes to make with the ci/cd. 

I was planning to just copy paste barter-data-rs, etc, into this repo. 

Any other considerations you can think of other than ci/cd ?

**Comment by liamwh** [comment]
I'm on vacation so on mobile without diving too deep into it, but I recall that maybe it's best that in the Cargo.toml files the crates should refer to each other using a local path and only when releasing use a specified version from crates.io. I do think Tokio can serve as a good reference here though. Happy to look more into it next week if needed 👍

**Comment by JakkuSakura** [comment]
I have experience making this move.
usually it's
1. move current repo into workspace
2. move other crates into same repo
3. change path in cargomtoml
4. merge and test CI/CD

**Comment by just-a-stream** [comment]
Thanks for the insight @JakkuSakura.

Do you know what the impact is on `cargo publish`-ing new crate versions to crates.io?

**Comment by JakkuSakura** [comment]
Cargo will notify you to add both path and version for a local dep in Cargo.toml. If the check doesn't pass, it won't publish. 
A caveat is that one need to publish the crates topologically. Cargo doesn't support publishing recursively yet

**Comment by just-a-stream** [comment]
Now that https://github.com/barter-rs/barter-rs/pull/35 is merged i'm closing this! :)
