### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by c10k-cc** [barter-rs/barter-rs#8]
# Update docs

## Summary

This issue / proposal attempts to address the project's need for a proper documentation update.

## Description

Type of docs which need to be updated / added (including but not limited to):
* project-related docs
  * rust docs
    * Rust doc-string comments inside the code files which gets auto-rendered to API reference docs - [see more here](https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html)
    * fix cross-linking / cross-referencing
  * `README.md`
    * file needs to be properly re-structured to reference all other markdown files proposed below
    * sections need to be sorted by the degree of complexity / depth of the topic covered
  * `ARCHITECTURE.md`
    * describes the project architecture 
    * could contain an embedded diagrams (UML or less formal) & flowcharts
  * Concepts
    * covering various concepts (theoretical or otherwise) introduced by the project
    * glossary of terms for the project
  * Examples
    * simple & trivial examples covering various project functionalities
  * Tutorial
    * proper user guide
  * Quick start
    * see 2 sections above
* repo-related docs
  * `CONTRIBUTING.md`
    * contains instructions on how to contribute
    * how to write code, tests, docs, git commit, git branches / workflow, setup dev environment etc
  * `MAINTAINING.md`
    * contains instructions on how to maintain the repo
    * how to manage & review issues / pull requests, organise the project board etc
  * `CODE_OF_CONDUCT.md`
    * bullshit file covering various topics related to political correctness, inclusivity, racism, sexuality, hate speech, profanity etc.
    * mainly used as a diplomatic no-responsibility disclaimer guarding authors & maintainers from consequences of stupid shit & abuse some degenerate contributor might do and ruin the things for the whole community
    * nice to have, but definitely lowest priority ever
* dedicated docs site / wiki pages
  * _GitHub Wiki pages_?
  * currently redundant?

**Comment by Traumflug** [comment]
Rather than planning for top-notch documentation, a simple set of instruction on how to get the example or these code snippets running at all would be a huge win. Is it just `git clone ... cargo run` ? There's zero hint on how to get things going, no hint on how the GUI(?) or CLI output looks like.

**Comment by min2sia** [comment]
> Rather than planning for top-notch documentation, a simple set of instruction on how to get the example or these code snippets running at all would be a huge win. Is it just `git clone ... cargo run` ? There's zero hint on how to get things going, no hint on how the GUI(?) or CLI output looks like.

Fully agree. A quick start guide would be really nice.

**Comment by DAMIEN-C00KE** [comment]
> Rather than planning for top-notch documentation, a simple set of instruction on how to get the example or these code snippets running at all would be a huge win. Is it just `git clone ... cargo run` ? There's zero hint on how to get things going, no hint on how the GUI(?) or CLI output looks like.

Great Idea. This is something I'd be happy to help with, and will look into.

**Comment by just-a-stream** [comment]
I'm back from a hiatus. Keeping this open as it contains some great ideas that can be actioned after up-coming refactors.
